/* ============================================
   Vocabulary Audio — Pronunciation Manifest
   270 key driving terms with TTS audio
   Generated via GCP Chirp 3 HD (fr-FR)
   ============================================ */

const VOCAB_AUDIO = {
  // --- Batch 5: 35 new words (Session 24) ---
  "infraction": "assets/audio/vocab/infraction.mp3",
  "engagé": "assets/audio/vocab/engage.mp3",
  "engage": "assets/audio/vocab/engage.mp3",
  "couper le moteur": "assets/audio/vocab/couper-le-moteur.mp3",
  "franchissement": "assets/audio/vocab/franchissement.mp3",
  "au pas": "assets/audio/vocab/au-pas.mp3",
  "interdiction de dépasser": "assets/audio/vocab/interdiction-de-depasser.mp3",
  "interdiction de depasser": "assets/audio/vocab/interdiction-de-depasser.mp3",
  "montant": "assets/audio/vocab/montant.mp3",
  "dépassement autorisé": "assets/audio/vocab/depassement-autorise.mp3",
  "depassement autorise": "assets/audio/vocab/depassement-autorise.mp3",
  "démarrer": "assets/audio/vocab/demarrer.mp3",
  "demarrer": "assets/audio/vocab/demarrer.mp3",
  "dépasser par la droite": "assets/audio/vocab/depasser-par-la-droite.mp3",
  "depasser par la droite": "assets/audio/vocab/depasser-par-la-droite.mp3",
  "losange jaune": "assets/audio/vocab/losange-jaune.mp3",
  "sens inverse": "assets/audio/vocab/sens-inverse.mp3",
  "triangle inversé": "assets/audio/vocab/triangle-inverse.mp3",
  "triangle inverse": "assets/audio/vocab/triangle-inverse.mp3",
  "pente": "assets/audio/vocab/pente.mp3",
  "sommet d'une côte": "assets/audio/vocab/sommet-d-une-cote.mp3",
  "sommet d'une cote": "assets/audio/vocab/sommet-d-une-cote.mp3",
  "anticiper": "assets/audio/vocab/anticiper.mp3",
  "certificat d'immatriculation": "assets/audio/vocab/certificat-d-immatriculation.mp3",
  "arrêt obligatoire": "assets/audio/vocab/arret-obligatoire.mp3",
  "arret obligatoire": "assets/audio/vocab/arret-obligatoire.mp3",
  "voyant": "assets/audio/vocab/voyant.mp3",
  "bouchon": "assets/audio/vocab/bouchon.mp3",
  "zone piétonne": "assets/audio/vocab/zone-pietonne.mp3",
  "zone pietonne": "assets/audio/vocab/zone-pietonne.mp3",
  "conducteur novice": "assets/audio/vocab/conducteur-novice.mp3",
  "vigilance": "assets/audio/vocab/vigilance.mp3",
  "feux tricolores": "assets/audio/vocab/feux-tricolores.mp3",
  "arrêt et stationnement interdits": "assets/audio/vocab/arret-et-stationnement-interdits.mp3",
  "arret et stationnement interdits": "assets/audio/vocab/arret-et-stationnement-interdits.mp3",
  "fourrière": "assets/audio/vocab/fourriere.mp3",
  "fourriere": "assets/audio/vocab/fourriere.mp3",
  "stationnement autorisé": "assets/audio/vocab/stationnement-autorise.mp3",
  "stationnement autorise": "assets/audio/vocab/stationnement-autorise.mp3",
  "tableau de bord": "assets/audio/vocab/tableau-de-bord.mp3",
  "appels de phares": "assets/audio/vocab/appels-de-phares.mp3",
  "files parallèles": "assets/audio/vocab/files-paralleles.mp3",
  "files paralleles": "assets/audio/vocab/files-paralleles.mp3",
  "mise en circulation": "assets/audio/vocab/mise-en-circulation.mp3",
  "numéro d'urgence européen": "assets/audio/vocab/numero-d-urgence-europeen.mp3",
  "numero d'urgence europeen": "assets/audio/vocab/numero-d-urgence-europeen.mp3",
  "intersection sans signalisation": "assets/audio/vocab/intersection-sans-signalisation.mp3",
  "chevaucher": "assets/audio/vocab/chevaucher.mp3",
  "feux de brouillard avant": "assets/audio/vocab/feux-de-brouillard-avant.mp3",
  "appel de phares": "assets/audio/vocab/appel-de-phares.mp3",
  "micro-sommeil": "assets/audio/vocab/micro-sommeil.mp3",
  // --- Batch 4: 50 new words (Session 22) ---
  "usager vulnérable": "assets/audio/vocab/usager-vulnerable.mp3",
  "usager vulnerable": "assets/audio/vocab/usager-vulnerable.mp3",
  "panneau d'obligation": "assets/audio/vocab/panneau-d-obligation.mp3",
  "panneau de danger": "assets/audio/vocab/panneau-de-danger.mp3",
  "se rabattre": "assets/audio/vocab/se-rabattre.mp3",
  "en amont": "assets/audio/vocab/en-amont.mp3",
  "voie ferrée": "assets/audio/vocab/voie-ferree.mp3",
  "voie ferree": "assets/audio/vocab/voie-ferree.mp3",
  "issue de secours": "assets/audio/vocab/issue-de-secours.mp3",
  "stage de sensibilisation": "assets/audio/vocab/stage-de-sensibilisation.mp3",
  "gilet de haute visibilité": "assets/audio/vocab/gilet-de-haute-visibilite.mp3",
  "gilet de haute visibilite": "assets/audio/vocab/gilet-de-haute-visibilite.mp3",
  "feu orange clignotant": "assets/audio/vocab/feu-orange-clignotant.mp3",
  "route de montagne": "assets/audio/vocab/route-de-montagne.mp3",
  "panneau directionnel": "assets/audio/vocab/panneau-directionnel.mp3",
  "somnolence": "assets/audio/vocab/somnolence.mp3",
  "borne de recharge": "assets/audio/vocab/borne-de-recharge.mp3",
  "sens de la circulation": "assets/audio/vocab/sens-de-la-circulation.mp3",
  "véhicule électrique": "assets/audio/vocab/vehicule-electrique.mp3",
  "vehicule electrique": "assets/audio/vocab/vehicule-electrique.mp3",
  "passage piétons": "assets/audio/vocab/passage-pietons.mp3",
  "passage pietons": "assets/audio/vocab/passage-pietons.mp3",
  "s'engager": "assets/audio/vocab/s-engager.mp3",
  "permis à points": "assets/audio/vocab/permis-a-points.mp3",
  "permis a points": "assets/audio/vocab/permis-a-points.mp3",
  "téléphone tenu en main": "assets/audio/vocab/telephone-tenu-en-main.mp3",
  "telephone tenu en main": "assets/audio/vocab/telephone-tenu-en-main.mp3",
  "dépassement par la droite": "assets/audio/vocab/depassement-par-la-droite.mp3",
  "depassement par la droite": "assets/audio/vocab/depassement-par-la-droite.mp3",
  "sommet de côte": "assets/audio/vocab/sommet-de-cote.mp3",
  "sommet de cote": "assets/audio/vocab/sommet-de-cote.mp3",
  "virage sans visibilité": "assets/audio/vocab/virage-sans-visibilite.mp3",
  "virage sans visibilite": "assets/audio/vocab/virage-sans-visibilite.mp3",
  "consommation de carburant": "assets/audio/vocab/consommation-de-carburant.mp3",
  "frein moteur": "assets/audio/vocab/frein-moteur.mp3",
  "vignette Crit'Air": "assets/audio/vocab/vignette-crit-air.mp3",
  "vignette crit'air": "assets/audio/vocab/vignette-crit-air.mp3",
  "agent de police": "assets/audio/vocab/agent-de-police.mp3",
  "arrêt complet": "assets/audio/vocab/arret-complet.mp3",
  "arret complet": "assets/audio/vocab/arret-complet.mp3",
  "ligne d'arrêt": "assets/audio/vocab/ligne-d-arret.mp3",
  "ligne d'arret": "assets/audio/vocab/ligne-d-arret.mp3",
  "rétrécissement de chaussée": "assets/audio/vocab/retrecissement-de-chaussee.mp3",
  "retrecissement de chaussee": "assets/audio/vocab/retrecissement-de-chaussee.mp3",
  "panneau de direction": "assets/audio/vocab/panneau-de-direction.mp3",
  "route départementale": "assets/audio/vocab/route-departementale.mp3",
  "route departementale": "assets/audio/vocab/route-departementale.mp3",
  "voie de décélération": "assets/audio/vocab/voie-de-deceleration.mp3",
  "voie de deceleration": "assets/audio/vocab/voie-de-deceleration.mp3",
  "panneau d'interdiction": "assets/audio/vocab/panneau-d-interdiction.mp3",
  "clé sur le contact": "assets/audio/vocab/cle-sur-le-contact.mp3",
  "cle sur le contact": "assets/audio/vocab/cle-sur-le-contact.mp3",
  "feux rouges clignotants": "assets/audio/vocab/feux-rouges-clignotants.mp3",
  "sortie de secours": "assets/audio/vocab/sortie-de-secours.mp3",
  "pause": "assets/audio/vocab/pause.mp3",
  "pictogramme": "assets/audio/vocab/pictogramme.mp3",
  "arrêté municipal": "assets/audio/vocab/arrete-municipal.mp3",
  "arrete municipal": "assets/audio/vocab/arrete-municipal.mp3",
  "bouche d'incendie": "assets/audio/vocab/bouche-d-incendie.mp3",
  "braquer les roues": "assets/audio/vocab/braquer-les-roues.mp3",
  "carte mobilité inclusion": "assets/audio/vocab/carte-mobilite-inclusion.mp3",
  "carte mobilite inclusion": "assets/audio/vocab/carte-mobilite-inclusion.mp3",
  "place handicapée": "assets/audio/vocab/place-handicapee.mp3",
  "place handicapee": "assets/audio/vocab/place-handicapee.mp3",
  "stationnement très gênant": "assets/audio/vocab/stationnement-tres-genant.mp3",
  "stationnement tres genant": "assets/audio/vocab/stationnement-tres-genant.mp3",
  "autobus scolaire": "assets/audio/vocab/autobus-scolaire.mp3",
  "canne blanche": "assets/audio/vocab/canne-blanche.mp3",
  "mise en fourrière": "assets/audio/vocab/mise-en-fourriere.mp3",
  "mise en fourriere": "assets/audio/vocab/mise-en-fourriere.mp3",
  "contre-visite": "assets/audio/vocab/contre-visite.mp3",
  "déviation": "assets/audio/vocab/deviation.mp3",
  "deviation": "assets/audio/vocab/deviation.mp3",
  // --- Batch 2: 55 new words (Session 21) ---
  "arrêt": "assets/audio/vocab/arret.mp3",
  "voie": "assets/audio/vocab/voie.mp3",
  "panne": "assets/audio/vocab/panne.mp3",
  "stationnement": "assets/audio/vocab/stationnement.mp3",
  "panneau": "assets/audio/vocab/panneau.mp3",
  "piéton": "assets/audio/vocab/pieton.mp3",
  "pieton": "assets/audio/vocab/pieton.mp3",
  "obligation": "assets/audio/vocab/obligation.mp3",
  "dépasser": "assets/audio/vocab/depasser.mp3",
  "depasser": "assets/audio/vocab/depasser.mp3",
  "intersection": "assets/audio/vocab/intersection.mp3",
  "signalisation": "assets/audio/vocab/signalisation.mp3",
  "klaxonner": "assets/audio/vocab/klaxonner.mp3",
  "ralentir": "assets/audio/vocab/ralentir.mp3",
  "interdiction": "assets/audio/vocab/interdiction.mp3",
  "secours": "assets/audio/vocab/secours.mp3",
  "visibilité": "assets/audio/vocab/visibilite.mp3",
  "visibilite": "assets/audio/vocab/visibilite.mp3",
  "croisement": "assets/audio/vocab/croisement.mp3",
  "barrière": "assets/audio/vocab/barriere.mp3",
  "barriere": "assets/audio/vocab/barriere.mp3",
  "stationner": "assets/audio/vocab/stationner.mp3",
  "cycliste": "assets/audio/vocab/cycliste.mp3",
  "assurance": "assets/audio/vocab/assurance.mp3",
  "clignotant": "assets/audio/vocab/clignotant.mp3",
  "zone 30": "assets/audio/vocab/zone-30.mp3",
  "permis de conduire": "assets/audio/vocab/permis-de-conduire.mp3",
  "en agglomération": "assets/audio/vocab/en-agglomeration.mp3",
  "en agglomeration": "assets/audio/vocab/en-agglomeration.mp3",
  "céder le passage": "assets/audio/vocab/ceder-le-passage.mp3",
  "franchir": "assets/audio/vocab/franchir.mp3",
  "tramway": "assets/audio/vocab/tramway.mp3",
  "poids lourd": "assets/audio/vocab/poids-lourd.mp3",
  "feu rouge": "assets/audio/vocab/feu-rouge.mp3",
  "convoi": "assets/audio/vocab/convoi.mp3",
  "reculer": "assets/audio/vocab/reculer.mp3",
  "feux de brouillard": "assets/audio/vocab/feux-de-brouillard.mp3",
  "carte grise": "assets/audio/vocab/carte-grise.mp3",
  "protéger": "assets/audio/vocab/proteger.mp3",
  "proteger": "assets/audio/vocab/proteger.mp3",
  "route prioritaire": "assets/audio/vocab/route-prioritaire.mp3",
  "hors agglomération": "assets/audio/vocab/hors-agglomeration.mp3",
  "hors agglomeration": "assets/audio/vocab/hors-agglomeration.mp3",
  "secourir": "assets/audio/vocab/secourir.mp3",
  "péage": "assets/audio/vocab/peage.mp3",
  "peage": "assets/audio/vocab/peage.mp3",
  "fatigue": "assets/audio/vocab/fatigue.mp3",
  "sens unique": "assets/audio/vocab/sens-unique.mp3",
  "demi-tour": "assets/audio/vocab/demi-tour.mp3",
  "distance latérale": "assets/audio/vocab/distance-laterale.mp3",
  "distance laterale": "assets/audio/vocab/distance-laterale.mp3",
  "manoeuvre": "assets/audio/vocab/manoeuvre.mp3",
  "remorque": "assets/audio/vocab/remorque.mp3",
  "zone de rencontre": "assets/audio/vocab/zone-de-rencontre.mp3",
  "incendie": "assets/audio/vocab/incendie.mp3",
  "accotement": "assets/audio/vocab/accotement.mp3",
  "giratoire": "assets/audio/vocab/giratoire.mp3",
  "contravention": "assets/audio/vocab/contravention.mp3",
  "immatriculation": "assets/audio/vocab/immatriculation.mp3",
  "priorité absolue": "assets/audio/vocab/priorite-absolue.mp3",
  "priorite absolue": "assets/audio/vocab/priorite-absolue.mp3",
  "limitation de vitesse": "assets/audio/vocab/limitation-de-vitesse.mp3",
  "zigzag": "assets/audio/vocab/zigzag.mp3",
  "véhicule prioritaire": "assets/audio/vocab/vehicule-prioritaire.mp3",
  "vehicule prioritaire": "assets/audio/vocab/vehicule-prioritaire.mp3",
  "bande d'arrêt d'urgence": "assets/audio/vocab/bande-d-arret-d-urgence.mp3",
  "bande d'arret d'urgence": "assets/audio/vocab/bande-d-arret-d-urgence.mp3",
  // --- Batch 3: 50 new words (Session 21b) ---
  "par la droite": "assets/audio/vocab/par-la-droite.mp3",
  "par la gauche": "assets/audio/vocab/par-la-gauche.mp3",
  "alerter": "assets/audio/vocab/alerter.mp3",
  "panneau rond": "assets/audio/vocab/panneau-rond.mp3",
  "voie de gauche": "assets/audio/vocab/voie-de-gauche.mp3",
  "faire demi-tour": "assets/audio/vocab/faire-demi-tour.mp3",
  "stationnement payant": "assets/audio/vocab/stationnement-payant.mp3",
  "triangulaire": "assets/audio/vocab/triangulaire.mp3",
  "côté droit": "assets/audio/vocab/cote-droit.mp3",
  "cote droit": "assets/audio/vocab/cote-droit.mp3",
  "éclairé": "assets/audio/vocab/eclaire.mp3",
  "eclaire": "assets/audio/vocab/eclaire.mp3",
  "côte": "assets/audio/vocab/cote.mp3",
  "cote": "assets/audio/vocab/cote.mp3",
  "bord rouge": "assets/audio/vocab/bord-rouge.mp3",
  "ligne jaune": "assets/audio/vocab/ligne-jaune.mp3",
  "bus scolaire": "assets/audio/vocab/bus-scolaire.mp3",
  "zone de travaux": "assets/audio/vocab/zone-de-travaux.mp3",
  "voie de droite": "assets/audio/vocab/voie-de-droite.mp3",
  "taux d'alcool": "assets/audio/vocab/taux-d-alcool.mp3",
  "alternat": "assets/audio/vocab/alternat.mp3",
  "gyrophare": "assets/audio/vocab/gyrophare.mp3",
  "impasse": "assets/audio/vocab/impasse.mp3",
  "voie publique": "assets/audio/vocab/voie-publique.mp3",
  "signalisation temporaire": "assets/audio/vocab/signalisation-temporaire.mp3",
  "route nationale": "assets/audio/vocab/route-nationale.mp3",
  "double file": "assets/audio/vocab/double-file.mp3",
  "frein à main": "assets/audio/vocab/frein-a-main.mp3",
  "frein a main": "assets/audio/vocab/frein-a-main.mp3",
  "sirène": "assets/audio/vocab/sirene.mp3",
  "sirene": "assets/audio/vocab/sirene.mp3",
  "sens de circulation": "assets/audio/vocab/sens-de-circulation.mp3",
  "voie réservée": "assets/audio/vocab/voie-reservee.mp3",
  "voie reservee": "assets/audio/vocab/voie-reservee.mp3",
  "délit": "assets/audio/vocab/delit.mp3",
  "delit": "assets/audio/vocab/delit.mp3",
  "période probatoire": "assets/audio/vocab/periode-probatoire.mp3",
  "periode probatoire": "assets/audio/vocab/periode-probatoire.mp3",
  "voie du milieu": "assets/audio/vocab/voie-du-milieu.mp3",
  "attestation d'assurance": "assets/audio/vocab/attestation-d-assurance.mp3",
  "numéro d'urgence": "assets/audio/vocab/numero-d-urgence.mp3",
  "numero d'urgence": "assets/audio/vocab/numero-d-urgence.mp3",
  "losange": "assets/audio/vocab/losange.mp3",
  "feu orange": "assets/audio/vocab/feu-orange.mp3",
  "signalisation permanente": "assets/audio/vocab/signalisation-permanente.mp3",
  "horodateur": "assets/audio/vocab/horodateur.mp3",
  "zone bleue": "assets/audio/vocab/zone-bleue.mp3",
  "temps de pluie": "assets/audio/vocab/temps-de-pluie.mp3",
  "alcoolémie": "assets/audio/vocab/alcoolemie.mp3",
  "alcoolemie": "assets/audio/vocab/alcoolemie.mp3",
  "descendant": "assets/audio/vocab/descendant.mp3",
  "passage étroit": "assets/audio/vocab/passage-etroit.mp3",
  "passage etroit": "assets/audio/vocab/passage-etroit.mp3",
  "route étroite": "assets/audio/vocab/route-etroite.mp3",
  "route etroite": "assets/audio/vocab/route-etroite.mp3",
  "pression des pneus": "assets/audio/vocab/pression-des-pneus.mp3",
  "disque de stationnement": "assets/audio/vocab/disque-de-stationnement.mp3",
  "suspension du permis": "assets/audio/vocab/suspension-du-permis.mp3",
  "excès de vitesse": "assets/audio/vocab/exces-de-vitesse.mp3",
  "exces de vitesse": "assets/audio/vocab/exces-de-vitesse.mp3",
  "chevron": "assets/audio/vocab/chevron.mp3",
  "disque a": "assets/audio/vocab/disque-a.mp3",
  "fond bleu": "assets/audio/vocab/fond-bleu.mp3",
  // --- Batch 1: 50 original words (Session 20) ---
  "agglomération": "assets/audio/vocab/agglomeration.mp3",
  "priorité à droite": "assets/audio/vocab/priorite-a-droite.mp3",
  "cédez le passage": "assets/audio/vocab/cedez-le-passage.mp3",
  "cedez le passage": "assets/audio/vocab/cedez-le-passage.mp3",
  "feu tricolore": "assets/audio/vocab/feu-tricolore.mp3",
  "rond-point": "assets/audio/vocab/rond-point.mp3",
  "dépassement": "assets/audio/vocab/depassement.mp3",
  "depassement": "assets/audio/vocab/depassement.mp3",
  "ligne continue": "assets/audio/vocab/ligne-continue.mp3",
  "ligne discontinue": "assets/audio/vocab/ligne-discontinue.mp3",
  "sens interdit": "assets/audio/vocab/sens-interdit.mp3",
  "stationnement interdit": "assets/audio/vocab/stationnement-interdit.mp3",
  "arrêt interdit": "assets/audio/vocab/arret-interdit.mp3",
  "arret interdit": "assets/audio/vocab/arret-interdit.mp3",
  "passage piéton": "assets/audio/vocab/passage-pieton.mp3",
  "passage pieton": "assets/audio/vocab/passage-pieton.mp3",
  "piste cyclable": "assets/audio/vocab/piste-cyclable.mp3",
  "voie de circulation": "assets/audio/vocab/voie-de-circulation.mp3",
  "vitesse maximale": "assets/audio/vocab/vitesse-maximale.mp3",
  "distance de sécurité": "assets/audio/vocab/distance-de-securite.mp3",
  "distance de securite": "assets/audio/vocab/distance-de-securite.mp3",
  "distance de freinage": "assets/audio/vocab/distance-de-freinage.mp3",
  "freinage d'urgence": "assets/audio/vocab/freinage-d-urgence.mp3",
  "aquaplaning": "assets/audio/vocab/aquaplaning.mp3",
  "verglas": "assets/audio/vocab/verglas.mp3",
  "brouillard": "assets/audio/vocab/brouillard.mp3",
  "feux de croisement": "assets/audio/vocab/feux-de-croisement.mp3",
  "feux de route": "assets/audio/vocab/feux-de-route.mp3",
  "feux de détresse": "assets/audio/vocab/feux-de-detresse.mp3",
  "feux de detresse": "assets/audio/vocab/feux-de-detresse.mp3",
  "feux de position": "assets/audio/vocab/feux-de-position.mp3",
  "ceinture de sécurité": "assets/audio/vocab/ceinture-de-securite.mp3",
  "ceinture de securite": "assets/audio/vocab/ceinture-de-securite.mp3",
  "permis probatoire": "assets/audio/vocab/permis-probatoire.mp3",
  "contrôle technique": "assets/audio/vocab/controle-technique.mp3",
  "controle technique": "assets/audio/vocab/controle-technique.mp3",
  "constat amiable": "assets/audio/vocab/constat-amiable.mp3",
  "taux d'alcoolémie": "assets/audio/vocab/taux-d-alcoolemie.mp3",
  "taux d'alcoolemie": "assets/audio/vocab/taux-d-alcoolemie.mp3",
  "éthylotest": "assets/audio/vocab/ethylotest.mp3",
  "ethylotest": "assets/audio/vocab/ethylotest.mp3",
  "gilet réfléchissant": "assets/audio/vocab/gilet-reflechissant.mp3",
  "gilet reflechissant": "assets/audio/vocab/gilet-reflechissant.mp3",
  "triangle de présignalisation": "assets/audio/vocab/triangle-de-presignalisation.mp3",
  "triangle de presignalisation": "assets/audio/vocab/triangle-de-presignalisation.mp3",
  "passage à niveau": "assets/audio/vocab/passage-a-niveau.mp3",
  "passage a niveau": "assets/audio/vocab/passage-a-niveau.mp3",
  "tunnel": "assets/audio/vocab/tunnel.mp3",
  "autoroute": "assets/audio/vocab/autoroute.mp3",
  "chaussée": "assets/audio/vocab/chaussee.mp3",
  "chaussee": "assets/audio/vocab/chaussee.mp3",
  "trottoir": "assets/audio/vocab/trottoir.mp3",
  "carrefour": "assets/audio/vocab/carrefour.mp3",
  "virage": "assets/audio/vocab/virage.mp3",
  "ralentisseur": "assets/audio/vocab/ralentisseur.mp3",
  "panneau de signalisation": "assets/audio/vocab/panneau-de-signalisation.mp3",
  "amende": "assets/audio/vocab/amende.mp3",
  "retrait de points": "assets/audio/vocab/retrait-de-points.mp3",
  "conduite accompagnée": "assets/audio/vocab/conduite-accompagnee.mp3",
  "conduite accompagnee": "assets/audio/vocab/conduite-accompagnee.mp3",
  "éco-conduite": "assets/audio/vocab/eco-conduite.mp3",
  "eco-conduite": "assets/audio/vocab/eco-conduite.mp3",
  "angle mort": "assets/audio/vocab/angle-mort.mp3",
  "champ de vision": "assets/audio/vocab/champ-de-vision.mp3",
  "klaxon": "assets/audio/vocab/klaxon.mp3",
  "rétroviseur": "assets/audio/vocab/retroviseur.mp3",
  "retroviseur": "assets/audio/vocab/retroviseur.mp3",
  // --- Batch 5: 27 new words (Session 23) ---
  "arrêt de bus": "assets/audio/vocab/arret-de-bus.mp3",
  "arret de bus": "assets/audio/vocab/arret-de-bus.mp3",
  "adhérence": "assets/audio/vocab/adherence.mp3",
  "adherence": "assets/audio/vocab/adherence.mp3",
  "croix de Saint-André": "assets/audio/vocab/croix-de-saint-andre.mp3",
  "croix de saint-andre": "assets/audio/vocab/croix-de-saint-andre.mp3",
  "temps sec": "assets/audio/vocab/temps-sec.mp3",
  "direction obligatoire": "assets/audio/vocab/direction-obligatoire.mp3",
  "feu rouge clignotant": "assets/audio/vocab/feu-rouge-clignotant.mp3",
  "ligne jaune continue": "assets/audio/vocab/ligne-jaune-continue.mp3",
  "stationnement gênant": "assets/audio/vocab/stationnement-genant.mp3",
  "stationnement genant": "assets/audio/vocab/stationnement-genant.mp3",
  "chien guide d'aveugle": "assets/audio/vocab/chien-guide-d-aveugle.mp3",
  "circulation inter-files": "assets/audio/vocab/circulation-inter-files.mp3",
  "convoi funéraire": "assets/audio/vocab/convoi-funeraire.mp3",
  "convoi funeraire": "assets/audio/vocab/convoi-funeraire.mp3",
  "deux-roues motorisé": "assets/audio/vocab/deux-roues-motorise.mp3",
  "deux-roues motorise": "assets/audio/vocab/deux-roues-motorise.mp3",
  "effet de souffle": "assets/audio/vocab/effet-de-souffle.mp3",
  "patineur en ligne": "assets/audio/vocab/patineur-en-ligne.mp3",
  "siège auto": "assets/audio/vocab/siege-auto.mp3",
  "siege auto": "assets/audio/vocab/siege-auto.mp3",
  "trottinette électrique": "assets/audio/vocab/trottinette-electrique.mp3",
  "trottinette electrique": "assets/audio/vocab/trottinette-electrique.mp3",
  "véhicule agricole": "assets/audio/vocab/vehicule-agricole.mp3",
  "vehicule agricole": "assets/audio/vocab/vehicule-agricole.mp3",
  "aire piétonne": "assets/audio/vocab/aire-pietonne.mp3",
  "aire pietonne": "assets/audio/vocab/aire-pietonne.mp3",
  "danger immédiat": "assets/audio/vocab/danger-immediat.mp3",
  "danger immediat": "assets/audio/vocab/danger-immediat.mp3",
  "feux diurnes": "assets/audio/vocab/feux-diurnes.mp3",
  "véhicule d'urgence": "assets/audio/vocab/vehicule-d-urgence.mp3",
  "vehicule d'urgence": "assets/audio/vocab/vehicule-d-urgence.mp3",
  "visibilité insuffisante": "assets/audio/vocab/visibilite-insuffisante.mp3",
  "visibilite insuffisante": "assets/audio/vocab/visibilite-insuffisante.mp3",
  "amende forfaitaire": "assets/audio/vocab/amende-forfaitaire.mp3",
  "capital de points": "assets/audio/vocab/capital-de-points.mp3",
  "éthylotest anti-démarrage": "assets/audio/vocab/ethylotest-anti-demarrage.mp3",
  "ethylotest anti-demarrage": "assets/audio/vocab/ethylotest-anti-demarrage.mp3",
  "monoxyde de carbone": "assets/audio/vocab/monoxyde-de-carbone.mp3",
  "engin agricole": "assets/audio/vocab/engin-agricole.mp3"
};

// Audio player singleton
const VocabAudio = {
  _audio: null,
  _cache: {},

  hasAudio(wordFr) {
    const key = wordFr.toLowerCase();
    return key in VOCAB_AUDIO;
  },

  play(wordFr) {
    const key = wordFr.toLowerCase();
    const path = VOCAB_AUDIO[key];
    if (!path) return false;

    if (this._audio) {
      this._audio.pause();
      this._audio.currentTime = 0;
    }

    if (this._cache[path]) {
      this._audio = this._cache[path];
    } else {
      this._audio = new Audio(path);
      this._cache[path] = this._audio;
    }

    this._audio.play().catch(() => {
      // Silently fail if audio can't play (e.g., no user interaction yet)
    });
    return true;
  }
};
