#!/usr/bin/env node
/**
 * build-vocab.js — Extracts deduplicated vocabulary from questions.json
 * Generates js/vocab-data.js and data/vocab.json
 *
 * Usage: node scripts/build-vocab.js
 *   or: npm run build:vocab
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const questionsPath = path.join(ROOT, 'data', 'questions.json');
const vocabJsonPath = path.join(ROOT, 'data', 'vocab.json');
const vocabJsPath = path.join(ROOT, 'js', 'vocab-data.js');
const manifestPath = path.join(ROOT, 'content-manifest.json');

// Read questions
const questions = JSON.parse(fs.readFileSync(questionsPath, 'utf8'));

// Extract and deduplicate vocabulary (same logic as Vocab.getAllVocab())
const vocabMap = new Map();
for (const q of questions) {
    if (!q.vocabulary) continue;
    for (const v of q.vocabulary) {
        const key = v.wordFr.toLowerCase();
        if (!vocabMap.has(key)) {
            vocabMap.set(key, {
                wordFr: v.wordFr,
                wordEn: v.wordEn,
                definition: v.definition || '',
                topic: q.topic,
                questionId: q.id
            });
        }
    }
}

const vocabArray = Array.from(vocabMap.values());

// Sort by topic then wordFr for deterministic output
vocabArray.sort((a, b) => a.topic.localeCompare(b.topic) || a.wordFr.localeCompare(b.wordFr));

// Write canonical vocab.json
fs.writeFileSync(vocabJsonPath, JSON.stringify(vocabArray, null, 2));

// Write JS module
const jsContent = `/* ==============================================
   VOCAB_DATA — Auto-generated by scripts/build-vocab.js
   DO NOT EDIT — edit data/questions.json vocabulary fields instead
   Total: ${vocabArray.length} unique words
   ============================================== */

const VOCAB_DATA = ${JSON.stringify(vocabArray, null, 2)};
`;
fs.writeFileSync(vocabJsPath, jsContent);

// Update manifest
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
manifest.vocabCount = vocabArray.length;
manifest.version = manifest.version + 1;
manifest.lastUpdated = new Date().toISOString().split('T')[0];
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

console.log(`Generated js/vocab-data.js`);
console.log(`  Unique words: ${vocabArray.length}`);
console.log(`  Topics covered: ${new Set(vocabArray.map(v => v.topic)).size}`);
console.log(`  Vocab JSON: data/vocab.json`);
console.log(`  Manifest: v${manifest.version} (${manifest.vocabCount} vocab)`);
